version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: bash -c "python manage.py migrate && gunicorn djangobnb_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/djangobnb_backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
