'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { useEffect, useState } from "react";
import { getUserId } from "./lib/actions";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{children: React.ReactNode;}>) {
  const [userId, setUserId] = useState<string | undefined>('');

  getUserId().then((id) => {
    setUserId(id);
  })

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar userId={userId} />
        <div className="pt-28 px-14">
          {children}
        </div>
      </body>
    </html>
  );
}
